- match:
    dependency_type: all
    update_type: "semver:minor"  # includes patch updates!

- match:
    dependency_name: cryptography
    update_type: all

- match:
    dependency_name: certifi
    update_type: all
