pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - label!=WIP
      - -draft
      - author!=renovate[bot] # renovate[bot] will handle their PR themselves
      - approved-reviews-by=@fedora-infra/bodhi
#     - "#changes-requested-reviews-by=0" -- handled by github branch protection
#     - status-success=DCO -- handled by github branch protection
#     - status-success=Pre-commit checks -- handled by github branch protection
#     - status-success=Diff-cover check -- handled by github branch protection
#     - status-success=Integration Tests (f42) -- handled by github branch protection
#     - status-success=Unit Tests (f42, bodhi-client) -- handled by github branch protection
#     - status-success=Unit Tests (f42, bodhi-messages) -- handled by github branch protection
#     - status-success=Unit Tests (f42, bodhi-server) -- handled by github branch protection
#     - status-success=Build Documentation (f42) -- handled by github branch protection
    actions:
      merge:
        method: rebase

  - name: backport 25.11
    actions:
      backport:
        branches:
          - "25.11"
    conditions:
      - label!=WIP
      - -draft
      - label=25.11-backports
