pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=WIP
  - approved-reviews-by=@fedora-infra/bodhi
  - status-success=DCO
  - status-success=f31-docs
  - status-success=f31-unit
  - status-success=f31-diff-cover
  - status-success=f31-integration
  - status-success=pip-docs
  - status-success=pip-flake8
  - status-success=pip-mypy
  - status-success=pip-pydocstyle
  - status-success=pip-unit
  - status-success=pip-diff-cover
  - status-success=pip-integration
  name: default
- actions:
    backport:
      branches:
      - '5.0'
  conditions:
  - label!=WIP
  - label=5.0-backports
  name: backport 5.0
- actions:
    backport:
      branches:
      - '5.1'
  conditions:
  - label!=WIP
  - label=5.1-backports
  name: backport 5.1
- actions:
    backport:
      branches:
      - '5.2'
  conditions:
  - label!=WIP
  - label=5.2-backports
  name: backport 5.2
- actions:
    backport:
      branches:
      - '5.3'
  conditions:
  - label!=WIP
  - label=5.3-backports
  name: backport 5.3
- actions:
    backport:
      branches:
      - '5.4'
  conditions:
  - label!=WIP
  - label=5.4-backports
  name: backport 5.4
