rules:
  default:
    automated_backport_labels:
      3.9-backports: "3.9"
      3.10-backports: "3.10"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - DCO
          - f27-docs
          - f27-flake8
          - f27-pydocstyle
          - f27-python2-unit
          - f27-python3-unit
          - f28-docs
          - f28-flake8
          - f28-pydocstyle
          - f28-python2-unit
          - f28-python3-unit
          - f29-docs
          - f29-flake8
          - f29-pydocstyle
          - f29-python2-unit
          - f29-python3-unit
          - pip-docs
          - pip-flake8
          - pip-pydocstyle
          - pip-python2-unit
          - pip-python3-unit
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
    merge_strategy:
      method: rebase
      rebase_fallback: none
