queue_rules:
  - name: default
    conditions:
    - label!=WIP
    - approved-reviews-by=@fedora-infra/bodhi
    - status-success=DCO
    - status-success=Pre-commit checks
    - status-success=Diff-cover check
    - status-success=Integration Tests (f34)
    - status-success=Integration Tests (f35)
    - status-success=Integration Tests (rawhide)
    - status-success=Unit Tests (f34, bodhi-client)
    - status-success=Unit Tests (f34, bodhi-messages)
    - status-success=Unit Tests (f34, bodhi-server)
    - status-success=Unit Tests (f35, bodhi-client)
    - status-success=Unit Tests (f35, bodhi-messages)
    - status-success=Unit Tests (f35, bodhi-server)
    - status-success=Unit Tests (pip, bodhi-client)
    - status-success=Unit Tests (pip, bodhi-messages)
    - status-success=Unit Tests (pip, bodhi-server)
    - status-success=Unit Tests (rawhide, bodhi-client)
    - status-success=Unit Tests (rawhide, bodhi-messages)
    - status-success=Unit Tests (rawhide, bodhi-server)
    - status-success=Build Documentation (f34)
    - status-success=Build Documentation (f35)
    - status-success=Build Documentation (pip)
    - status-success=Build Documentation (rawhide)

pull_request_rules:
- actions:
    queue:
      method: rebase
      name: default
  conditions:
  - label!=WIP
  - approved-reviews-by=@fedora-infra/bodhi
  - status-success=DCO
  - status-success=Pre-commit checks
  - status-success=Diff-cover check
  - status-success=Integration Tests (f34)
  - status-success=Integration Tests (f35)
  - status-success=Integration Tests (rawhide)
  - status-success=Unit Tests (f34, bodhi-client)
  - status-success=Unit Tests (f34, bodhi-messages)
  - status-success=Unit Tests (f34, bodhi-server)
  - status-success=Unit Tests (f35, bodhi-client)
  - status-success=Unit Tests (f35, bodhi-messages)
  - status-success=Unit Tests (f35, bodhi-server)
  - status-success=Unit Tests (pip, bodhi-client)
  - status-success=Unit Tests (pip, bodhi-messages)
  - status-success=Unit Tests (pip, bodhi-server)
  - status-success=Unit Tests (rawhide, bodhi-client)
  - status-success=Unit Tests (rawhide, bodhi-messages)
  - status-success=Unit Tests (rawhide, bodhi-server)
  - status-success=Build Documentation (f34)
  - status-success=Build Documentation (f35)
  - status-success=Build Documentation (pip)
  - status-success=Build Documentation (rawhide)
  name: default
- actions:
    backport:
      branches:
      - '5.6'
  conditions:
  - label!=WIP
  - label=5.6-backports
  name: backport 5.6
- actions:
    backport:
      branches:
      - '5.7'
  conditions:
  - label!=WIP
  - label=5.7-backports
  name: backport 5.7
