queue_rules:
  - name: default
    conditions:
    - status-success=DCO
    - status-success=Pre-commit checks
    - status-success=Diff-cover check
    - status-success=Integration Tests (f36)
    - status-success=Integration Tests (f37)
    - status-success=Unit Tests (f36, bodhi-client)
    - status-success=Unit Tests (f36, bodhi-messages)
    - status-success=Unit Tests (f36, bodhi-server)
    - status-success=Unit Tests (f37, bodhi-client)
    - status-success=Unit Tests (f37, bodhi-messages)
    - status-success=Unit Tests (f37, bodhi-server)
    - status-success=Unit Tests (pip, bodhi-client)
    - status-success=Unit Tests (pip, bodhi-messages)
    - status-success=Unit Tests (pip, bodhi-server)
    - status-success=Build Documentation (f36)
    - status-success=Build Documentation (f37)
    - status-success=Build Documentation (pip)


pull_request_rules:

- name: default
  actions:
    queue:
      method: rebase
      name: default
  conditions:
  - label!=WIP
  - -draft
  - approved-reviews-by=@fedora-infra/bodhi
  - "#changes-requested-reviews-by=0"
  - status-success=DCO
  - status-success=Pre-commit checks
  - status-success=Diff-cover check
  - status-success=Integration Tests (f36)
  - status-success=Integration Tests (f37)
  - status-success=Unit Tests (f36, bodhi-client)
  - status-success=Unit Tests (f36, bodhi-messages)
  - status-success=Unit Tests (f36, bodhi-server)
  - status-success=Unit Tests (f37, bodhi-client)
  - status-success=Unit Tests (f37, bodhi-messages)
  - status-success=Unit Tests (f37, bodhi-server)
  - status-success=Unit Tests (pip, bodhi-client)
  - status-success=Unit Tests (pip, bodhi-messages)
  - status-success=Unit Tests (pip, bodhi-server)
  - status-success=Build Documentation (f36)
  - status-success=Build Documentation (f37)
  - status-success=Build Documentation (pip)

- name: backport 7.0
  actions:
    backport:
      branches:
      - '7.0'
  conditions:
  - label!=WIP
  - -draft
  - label=7.0-backports

- name: backport 7.1
  actions:
    backport:
      branches:
      - '7.1'
  conditions:
  - label!=WIP
  - -draft
  - label=7.1-backports

- name: dependabot
  actions:
    queue:
      method: rebase
      name: default
  conditions:
  - label!=WIP
  - -draft
  - author=dependabot[bot]
  - approved-reviews-by=github-actions[bot]
  - "#changes-requested-reviews-by=0"
  - status-success=DCO
  - status-success=Pre-commit checks
  - status-success=Diff-cover check
  - status-success=Integration Tests (f36)
  - status-success=Integration Tests (f37)
  - status-success=Unit Tests (f36, bodhi-client)
  - status-success=Unit Tests (f36, bodhi-messages)
  - status-success=Unit Tests (f36, bodhi-server)
  - status-success=Unit Tests (f37, bodhi-client)
  - status-success=Unit Tests (f37, bodhi-messages)
  - status-success=Unit Tests (f37, bodhi-server)
  - status-success=Unit Tests (pip, bodhi-client)
  - status-success=Unit Tests (pip, bodhi-messages)
  - status-success=Unit Tests (pip, bodhi-server)
  - status-success=Build Documentation (f36)
  - status-success=Build Documentation (f37)
  - status-success=Build Documentation (pip)
