pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=WIP
  - approved-reviews-by=@fedora-infra/bodhi
  - status-success=DCO
  - status-success=f32-docs
  - status-success=f32-unit
  - status-success=f32-diff-cover
  - status-success=f33-docs
  - status-success=f33-unit
  - status-success=f33-diff-cover
  - status-success=pip-docs
  - status-success=pip-flake8
  - status-success=pip-mypy
  - status-success=pip-pydocstyle
  - status-success=pip-unit
  - status-success=pip-diff-cover
  name: default
- actions:
    backport:
      branches:
      - '5.6'
  conditions:
  - label!=WIP
  - label=5.6-backports
  name: backport 5.6
- actions:
    backport:
      branches:
      - '5.7'
  conditions:
  - label!=WIP
  - label=5.7-backports
  name: backport 5.7
