pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - approved-reviews-by=bowlofeggs
  - status-success=DCO
  - status-success=f28-docs
  - status-success=f28-flake8
  - status-success=f28-pydocstyle
  - status-success=f28-python2-unit
  - status-success=f28-python2-diff-cover
  - status-success=f28-python3-unit
  - status-success=f28-python3-diff-cover
  - status-success=f29-docs
  - status-success=f29-flake8
  - status-success=f29-pydocstyle
  - status-success=f29-python2-unit
  - status-success=f29-python2-diff-cover
  - status-success=f29-python3-unit
  - status-success=f29-python3-diff-cover
  - status-success=pip-docs
  - status-success=pip-flake8
  - status-success=pip-mypy
  - status-success=pip-pydocstyle
  - status-success=pip-python2-unit
  - status-success=pip-python2-diff-cover
  - status-success=pip-python3-unit
  - status-success=pip-python3-diff-cover
  - status-success=f29-python3-integration
  name: default
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=no-mergify
  - author=bowlofeggs
  - "#approved-reviews-by>=1"
  - status-success=DCO
  - status-success=f28-docs
  - status-success=f28-flake8
  - status-success=f28-pydocstyle
  - status-success=f28-python2-unit
  - status-success=f28-python2-diff-cover
  - status-success=f28-python3-unit
  - status-success=f28-python3-diff-cover
  - status-success=f29-docs
  - status-success=f29-flake8
  - status-success=f29-pydocstyle
  - status-success=f29-python2-unit
  - status-success=f29-python2-diff-cover
  - status-success=f29-python3-unit
  - status-success=f29-python3-diff-cover
  - status-success=pip-docs
  - status-success=pip-flake8
  - status-success=pip-mypy
  - status-success=pip-pydocstyle
  - status-success=pip-python2-unit
  - status-success=pip-python2-diff-cover
  - status-success=pip-python3-unit
  - status-success=pip-python3-diff-cover
  name: default-from-bowlofeggs
- actions:
    backport:
      branches:
      - '3.11'
  conditions:
  - label!=no-mergify
  - label=3.11-backports
  name: backport 3.11
- actions:
    backport:
      branches:
      - '3.12'
  conditions:
  - label!=no-mergify
  - label=3.12-backports
  name: backport 3.12
