rules:
  default:
    automated_backport_labels:
      3.9-backports: "3.9"
      3.10-backports: "3.10"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - DCO
          - flake8 tests (f27)
          - flake8 tests (f28)
          - flake8 tests (f29)
          - flake8 tests (pip)
          - pydocstyle tests (f27)
          - pydocstyle tests (f28)
          - pydocstyle tests (f29)
          - pydocstyle tests (pip)
          - docs tests (f27)
          - docs tests (f28)
          - docs tests (f29)
          - docs tests (pip)
          - unit tests (f27)
          - unit tests (f28)
          - unit tests (f29)
          - unit tests (pip)
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
    merge_strategy:
      method: rebase
      rebase_fallback: none
