pull_request_rules:
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=WIP
  - approved-reviews-by=@fedora-infra/bodhi
  - status-success=DCO
  - status-success=f29-docs
  - status-success=f29-unit
  - status-success=f29-diff-cover
  - status-success=f29-integration
  - status-success=f30-docs
  - status-success=f30-unit
  - status-success=f30-diff-cover
  - status-success=f30-integration
  - status-success=f31-docs
  - status-success=f31-unit
  - status-success=f31-diff-cover
  - status-success=f31-integration
  - status-success=pip-docs
  - status-success=pip-flake8
  - status-success=pip-mypy
  - status-success=pip-pydocstyle
  - status-success=pip-unit
  - status-success=pip-diff-cover
  - status-success=pip-integration
  name: default
- actions:
    merge:
      method: rebase
      rebase_fallback: null
      strict: true
  conditions:
  - label!=WIP
  - author=@fedora-infra/bodhi
  - "#approved-reviews-by>=1"
  - status-success=DCO
  - status-success=f29-docs
  - status-success=f29-unit
  - status-success=f29-diff-cover
  - status-success=f29-integration
  - status-success=f30-docs
  - status-success=f30-unit
  - status-success=f30-diff-cover
  - status-success=f30-integration
  - status-success=f31-docs
  - status-success=f31-unit
  - status-success=f31-diff-cover
  - status-success=f31-integration
  - status-success=pip-docs
  - status-success=pip-flake8
  - status-success=pip-mypy
  - status-success=pip-pydocstyle
  - status-success=pip-unit
  - status-success=pip-diff-cover
  - status-success=pip-integration
  name: default-from-bowlofeggs
- actions:
    backport:
      branches:
      - '3.12'
  conditions:
  - label!=WIP
  - label=3.12-backports
  name: backport 3.12
- actions:
    backport:
      branches:
      - '3.13'
  conditions:
  - label!=WIP
  - label=3.13-backports
  name: backport 3.13
- actions:
    backport:
      branches:
      - '3.14'
  conditions:
  - label!=WIP
  - label=3.14-backports
  name: backport 3.14
- actions:
    backport:
      branches:
      - '4.0'
  conditions:
  - label!=WIP
  - label=4.0-backports
  name: backport 4.0
- actions:
    backport:
      branches:
      - '4.1'
  conditions:
  - label!=WIP
  - label=4.1-backports
  name: backport 4.1
- actions:
    backport:
      branches:
      - '5.0'
  conditions:
  - label!=WIP
  - label=5.0-backports
  name: backport 5.0
