queue_rules:
  - name: default
    conditions:
    - status-success=DCO
    - status-success=Pre-commit checks
    - status-success=Diff-cover check
    - status-success=Integration Tests (f39)
    - status-success=Unit Tests (f39, bodhi-client)
    - status-success=Unit Tests (f39, bodhi-messages)
    - status-success=Unit Tests (f39, bodhi-server)
    - status-success=Unit Tests (pip, bodhi-client)
    - status-success=Unit Tests (pip, bodhi-messages)
    - status-success=Unit Tests (pip, bodhi-server)
    - status-success=Build Documentation (f39)
    - status-success=Build Documentation (pip)


pull_request_rules:

- name: default
  actions:
    queue:
      method: rebase
      name: default
  conditions:
  - label!=WIP
  - -draft
  - approved-reviews-by=@fedora-infra/bodhi
  - "#changes-requested-reviews-by=0"
  - status-success=DCO
  - status-success=Pre-commit checks
  - status-success=Diff-cover check
  - status-success=Integration Tests (f39)
  - status-success=Unit Tests (f39, bodhi-client)
  - status-success=Unit Tests (f39, bodhi-messages)
  - status-success=Unit Tests (f39, bodhi-server)
  - status-success=Unit Tests (pip, bodhi-client)
  - status-success=Unit Tests (pip, bodhi-messages)
  - status-success=Unit Tests (pip, bodhi-server)
  - status-success=Build Documentation (f39)
  - status-success=Build Documentation (pip)

- name: backport 8.0
  actions:
    backport:
      branches:
      - '8.0'
  conditions:
  - label!=WIP
  - -draft
  - label=8.0-backports

- name: backport 8.1
  actions:
    backport:
      branches:
      - '8.1'
  conditions:
  - label!=WIP
  - -draft
  - label=8.1-backports
