rules:
  default:
    automated_backport_labels:
      3.9-backports: "3.9"
    protection:
      required_status_checks:
        strict: true
        contexts:
          - DCO
          - default
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_approving_review_count: 1
    merge_strategy:
      method: rebase
      rebase_fallback: none
