queue_rules:
  - name: default
    conditions:
    - label!=WIP
    - approved-reviews-by=@fedora-infra/bodhi
    - status-success=DCO
    - status-success=fedora/check

pull_request_rules:
- actions:
    queue:
      method: rebase
      name: default
  conditions:
  - label!=WIP
  - approved-reviews-by=@fedora-infra/bodhi
  - status-success=DCO
  - status-success=fedora/check

  name: default
- actions:
    backport:
      branches:
      - '5.6'
  conditions:
  - label!=WIP
  - label=5.6-backports
  name: backport 5.6
- actions:
    backport:
      branches:
      - '5.7'
  conditions:
  - label!=WIP
  - label=5.7-backports
  name: backport 5.7
