---
- job:
    name: bodhi-pre-commit
    run: devel/ci/bodhi-pre-commit.yaml
    nodeset:
      nodes:
        name: bodhi-precommit-node
        label: zuul-worker-f34
- job:
    name: bodhi-unit-f34
    run: devel/ci/bodhi-unit.yaml
    nodeset:
      nodes:
        name: bodhi-unit-f34-node
        label: zuul-worker-f34
- job:
    name: bodhi-docs
    run: devel/ci/bodhi-docs.yaml
    nodeset:
      nodes:
        name: bodhi-docs-node
        label: zuul-worker-f34
- job:
    name: bodhi-pip
    run: devel/ci/bodhi-pip.yaml
    nodeset:
      nodes:
        name: bodhi-pip-node
        label: zuul-worker-f34
- job:
    name: bodhi-integration
    run: devel/ci/bodhi-integration.yaml
    nodeset: fedora-35-vm

- project:
    check:
      jobs:
        - bodhi-integration
        # - bodhi-pre-commit
        # - bodhi-unit-f34
        # - bodhi-pip
        # - bodhi-docs
