---
- job:
    name: bodhi-pre-commit
    run: devel/ci/pre-commit.yaml
    nodeset:
      nodes:
        name: bodhi-precommit-node
        label: zuul-worker-f34
- job:
    name: bodhi-unit-f34
    run: devel/ci/unit.yaml
    nodeset:
      nodes:
        name: bodhi-unit-f34-node
        label: zuul-worker-f34
- job:
    name: bodhi-docs
    run: devel/ci/docs.yaml
    nodeset:
      nodes:
        name: bodhi-docs-node
        label: zuul-worker-f34
- job:
    name: bodhi-pip
    run: devel/ci/pip.yaml
    nodeset:
      nodes:
        name: bodhi-pip-node
        label: zuul-worker-f34
- project:
    check:
      jobs:
        - bodhi-pre-commit
        - bodhi-unit-f34
        - bodhi-pip
        - bodhi-docs
