---
- job:
    name: bodhi-pre-commit
    run: devel/ci/bodhi-pre-commit.yaml
    nodeset:
      nodes:
        name: bodhi-precommit-node
        label: pod-python-f35
- job:
    name: bodhi-unit
    run: devel/ci/bodhi-unit.yaml
    nodeset:
      nodes:
        name: bodhi-unit-node
        label: pod-python-f33

- project:
    check:
      jobs:
        - bodhi-pre-commit
        - bodhi-unit
