#!/usr/bin/python -tt
""" Start script for bodhi """
from bodhi.commands import start, ConfigurationError

if __name__ == '__main__':
    try:
        start()
    except ConfigurationError, exc:
        import sys
        sys.stderr.write(str(exc))
        sys.exit(1)

