---
- hosts: all
  become: true
  become_method: sudo
  vars:
      ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Check if ipsilon.tinystage.test is reachable
      shell: "ping -c 5 ipsilon.tinystage.test"
      ignore_errors: yes
      register: ping_response
    
    - name: Give reason for failure
      fail:
        msg: Provisioning bodhi requires the base tinystage setup to be running.
      when: ping_response.rc != 0
  roles:
    - bodhi
