---
- hosts: all

  tasks:
    - name: List project directory on the test system
      command: "ls -al {{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    - name: prepare unit
      command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: sed -i '/pyramid_debugtoolbar/d' setup.py
    - name: prepare unit
      command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: sed -i '/pyramid_debugtoolbar/d' devel/development.ini.example
    - name: install deps
      become: true
      command: dnf -y install pungi python3-createrepo_c python3-devel python3-dnf python3-koji python3-librepo python3-setuptools python3-alembic python3-arrow python3-backoff python3-bleach python3-celery python3-click python3-colander python3-cornice python3-cornice-sphinx python3-dogpile-cache python3-fedora-messaging python3-feedgen python3-iniparse python3-jinja2 python3-markdown python3-mock python3-prometheus_client python3-psycopg2 python3-pylibravatar python3-pyramid python3-pyramid-fas-openid python3-pyramid-mako python3-bugzilla python3-fedora python3-pyyaml python3-responses python3-simplemediawiki python3-sphinx python3-sqlalchemy python3-sqlalchemy_schemadisplay python3-twisted python3-webob python3-webtest python3-whitenoise python3-pytest  python3-pytest-cov
    - name: prepare unit
      command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: mv devel/development.ini.example development.ini
    - name: create venv
      command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: "python3 -m venv --system-site-packages --without-pip .test-venv"
    - name: setup bodhi
      command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: ".test-venv/bin/python3 setup.py develop"
    - name: run tests
      command:
        chdir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
        cmd: ".test-venv/bin/python3 /usr/bin/py.test-3 -v bodhi/tests"
