FROM registry.fedoraproject.org/fedora:rawhide
LABEL maintainer="Randy Barlow <bowlofeggs@fedoraproject.org>"

RUN dnf upgrade -y
RUN dnf install --disablerepo rawhide-modular -y \
    createrepo_c \
    fedora-messaging \
    findutils \
    git \
    liberation-mono-fonts \
    make \
    python2-click \
    python2-fedora \
    python2-koji \
    python2-mock \
    python2-munch \
    python2-pytest-cov \
    python3-alembic \
    python3-arrow \
    python3-bleach \
    python3-bugzilla \
    python3-colander \
    python3-cornice \
    python3-cornice-sphinx \
    python3-createrepo_c \
    python3-diff-cover \
    python3-dogpile-cache \
    python3-fedmsg \
    python3-fedora \
    python3-feedgen \
    python3-flake8 \
    python3-hawkey \
    python3-kitchen \
    python3-koji \
    python3-libcomps \
    python3-librepo \
    python3-markdown \
    python3-mock \
    python3-munch \
    python3-pillow \
    python3-pydocstyle \
    python3-pylibravatar \
    python3-pyramid-fas-openid \
    python3-pyramid-mako \
    python3-pytest \
    python3-pytest-cov \
    python3-responses \
    python3-simplemediawiki \
    python3-sqlalchemy \
    python3-sqlalchemy_schemadisplay \
    python3-webtest \
    python3-yaml

# Fake pungi being installed so we can avoid it and all its dependencies
RUN ln -s /usr/bin/true /usr/bin/pungi-koji
VOLUME ["/results"]
WORKDIR /bodhi
CMD ["bash"]
COPY . /bodhi
RUN find /bodhi -name "*.pyc" -delete
RUN find /bodhi -name "*__pycache__" -delete
RUN rm -rf *.egg-info
RUN rm -rf /bodhi/docs/_build
RUN rm -rf /bodhi/docs/developer/docblocks
RUN sed -i '/pyramid_debugtoolbar/d' setup.py
RUN sed -i '/pyramid_debugtoolbar/d' devel/development.ini.example
RUN cp devel/development.ini.example development.ini
