FROM registry.fedoraproject.org/fedora:29
MAINTAINER "Randy Barlow" <bowlofeggs@fedoraproject.org>

# Work around a severe dnf/libsolv/glibc issue: https://pagure.io/releng/issue/7125
# This was suggested in a BZ comment: https://bugzilla.redhat.com/show_bug.cgi?id=1483553#c78
RUN dnf upgrade -y libsolv || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."
# The echo works around https://bugzilla.redhat.com/show_bug.cgi?id=1483553 and any other future dnf
# upgrade bugs.
RUN dnf upgrade -y || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."
RUN dnf install --disablerepo rawhide-modular -y \
    createrepo_c \
    findutils \
    git \
    liberation-mono-fonts \
    packagedb-cli \
    python2-createrepo_c \
    python2-hawkey \
    python2-jinja2 \
    python2-koji \
    python2-librepo \
    python2-yaml \
    python3-createrepo_c \
    python3-hawkey \
    python3-yaml \
    make \
    python2-arrow \
    python2-bleach \
    python2-colander \
    python2-dogpile-cache \
    python2-fedmsg \
    python2-feedgen \
    python2-iniparse \
    python2-kitchen \
    python2-markdown \
    python2-mock \
    python2-pillow \
    python2-pyramid-mako \
    python2-pyramid-tm \
    python2-pytest-cov \
    python2-responses \
    python2-sqlalchemy \
    python2-sqlalchemy_schemadisplay \
    python3-alembic \
    python3-arrow \
    python3-bleach \
    python3-colander \
    python3-diff-cover \
    python3-dogpile-cache \
    python3-fedmsg \
    python3-fedora \
    python3-feedgen \
    python3-flake8 \
    python3-kitchen \
    python3-libcomps \
    python3-markdown \
    python3-mock \
    python3-munch \
    python3-pillow \
    python3-pydocstyle \
    python3-pylibravatar \
    python3-pyramid-mako \
    python3-pyramid-tm \
    python3-pytest \
    python3-pytest-cov \
    python3-responses \
    python3-simplemediawiki \
    python3-sqlalchemy \
    python3-webtest \
    python2-alembic \
    python2-bugzilla \
    python2-cornice \
    python2-cornice-sphinx \
    python2-munch \
    python2-openid \
    python2-pylibravatar \
    python2-pyramid-fas-openid \
    python2-simplemediawiki \
    python3-cornice \
    python3-cornice-sphinx \
    python2-webtest \
    python3-pyramid-fas-openid \
    python2-libcomps

# Fake pungi being installed so we can avoid it and all its dependencies
RUN ln -s /usr/bin/true /usr/bin/pungi-koji
VOLUME ["/results"]
WORKDIR /bodhi
CMD ["bash"]
COPY . /bodhi
RUN find /bodhi -name "*.pyc" -delete
RUN find /bodhi -name "*__pycache__" -delete
RUN rm -rf *.egg-info
RUN rm -rf /bodhi/docs/_build
RUN rm -rf /bodhi/docs/developer/docblocks
RUN sed -i '/pyramid_debugtoolbar/d' setup.py
RUN sed -i '/pyramid_debugtoolbar/d' devel/development.ini.example
RUN cp devel/development.ini.example development.ini
