FROM registry.fedoraproject.org/fedora:FEDORA_RELEASE
MAINTAINER "Randy Barlow" <bowlofeggs@fedoraproject.org>

RUN dnf upgrade -y
RUN dnf install -y \
    git \
    liberation-mono-fonts \
    packagedb-cli \
    python2-arrow \
    python2-bleach \
    python2-cornice \
    python2-cornice-sphinx \
    python2-createrepo_c \
    python2-dogpile-cache \
    python2-fedmsg-atomic-composer \
    python2-flake8 \
    python2-iniparse \
    python2-koji \
    python2-librepo \
    python2-markdown \
    python2-mock \
    python2-pillow \
    python2-pytest-cov \
    python2-sqlalchemy_schemadisplay \
    python3-pydocstyle \
    python3-tox \
