FROM registry.fedoraproject.org/fedora:FEDORA_RELEASE
MAINTAINER "Randy Barlow" <bowlofeggs@fedoraproject.org>

# The echo works around https://bugzilla.redhat.com/show_bug.cgi?id=1483553 and any other future dnf
# upgrade bugs.
RUN dnf upgrade -y
RUN dnf install -y \
    git \
    liberation-mono-fonts \
    packagedb-cli \
    pungi \
    python2-cornice-sphinx \
    python2-createrepo_c \
    python2-jinja2 \
    python2-koji \
    python2-librepo \
