FROM bodhi-ci/pip
LABEL maintainer="Randy Barlow <bowlofeggs@fedoraproject.org>"
ENV VIRTUAL_ENV=/srv/venv
RUN pip-3 install mypy types-requests types-click
RUN poetry config virtualenvs.create false
