FROM registry.fedoraproject.org/fedora:29
LABEL maintainer="Randy Barlow <bowlofeggs@fedoraproject.org>"

# Work around a severe dnf/libsolv/glibc issue: https://pagure.io/releng/issue/7125
# This was suggested in a BZ comment: https://bugzilla.redhat.com/show_bug.cgi?id=1483553#c78
RUN dnf upgrade -y libsolv || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."
# The echo works around https://bugzilla.redhat.com/show_bug.cgi?id=1483553 and any other future dnf
# upgrade bugs.
RUN dnf upgrade -y || echo "We are not trying to test dnf upgrade, so ignoring dnf failure."
RUN dnf install --disablerepo rawhide-modular -y \
    createrepo_c \
    findutils \
    git \
    liberation-mono-fonts \
    packagedb-cli \
    python2-createrepo_c \
    python2-hawkey \
    python2-jinja2 \
    python2-koji \
    python2-librepo \
    python2-yaml \
    python3-createrepo_c \
    python3-hawkey \
    python3-yaml \
    createrepo_c \
    gcc \
    gcc-c++ \
    graphviz \
    python2-devel \
    python3-devel \
    python3-librepo \
    python3-simplemediawiki \
    redhat-rpm-config \
    python2-libcomps \
    python3-libcomps

COPY requirements.txt /bodhi/requirements.txt

RUN pip-2 install -r /bodhi/requirements.txt
RUN pip-3 install -r /bodhi/requirements.txt
RUN pip-2 install \
    diff-cover \
    mock \
    responses \
    pytest \
    pytest-cov \
    webtest
RUN pip-3 install \
    cornice_sphinx \
    diff-cover \
    flake8 \
    mock \
    responses \
    pydocstyle \
    pytest \
    pytest-cov \
    sqlalchemy_schemadisplay \
    webtest

# Fake pungi being installed so we can avoid it and all its dependencies
RUN ln -s /usr/bin/true /usr/bin/pungi-koji
VOLUME ["/results"]
WORKDIR /bodhi
CMD ["bash"]
COPY . /bodhi
RUN find /bodhi -name "*.pyc" -delete
RUN find /bodhi -name "*__pycache__" -delete
RUN rm -rf *.egg-info
RUN rm -rf /bodhi/docs/_build
RUN rm -rf /bodhi/docs/developer/docblocks
RUN sed -i '/pyramid_debugtoolbar/d' setup.py
RUN sed -i '/pyramid_debugtoolbar/d' devel/development.ini.example
# The Makefile is set to use sphinx-build-3, but the pip installed sphinx is just called
# sphinx-build.
RUN sed -i 's/sphinx-build-3/sphinx-build/' docs/Makefile
RUN cp devel/development.ini.example development.ini
