FROM registry.fedoraproject.org/fedora:35
LABEL maintainer="Mattia Verga <mattia.verga@fedoraproject.org>"

# RUN echo "fastestmirror=False" >> /etc/dnf/dnf.conf
# RUN echo "zchunk = False" >> /etc/dnf/dnf.conf

RUN dnf install -y \
    createrepo_c \
    fedora-messaging \
    findutils \
    git \
    make \
    pip \
    python3-alembic \
    python3-arrow \
    python3-authlib \
    python3-backoff \
    python3-bleach \
    python3-bugzilla \
    python3-celery \
    python3-click \
    python3-colander \
    python3-cornice \
    python3-createrepo_c \
    python3-devel \
    python3-diff-cover \
    python3-dnf \
    python3-dogpile-cache \
    python3-feedgen \
    python3-gssapi \
    python3-jinja2 \
    python3-koji \
    python3-libcomps \
    python3-librepo \
    python3-markdown \
    python3-munch \
    python3-openid \
    python3-psycopg2 \
    python3-prometheus_client \
    python3-pylibravatar \
    python3-pyramid \
    python3-pyramid-fas-openid \
    python3-pyramid-mako \
    python3-pytest \
    python3-pytest-cov \
    python3-pytest-mock \
    python3-responses \
    python3-simplemediawiki \
    python3-sphinx \
    python3-sqlalchemy \
    python3-sqlalchemy_schemadisplay \
    python3-waitress \
    python3-webtest \
    python3-wheel \
    python3-whitenoise \
    python3-yaml \
    rpm-build \
    rpmdevtools

# Fake pungi being installed so we can avoid it and all its dependencies
RUN ln -s /usr/bin/true /usr/bin/pungi-koji
VOLUME ["/results"]
WORKDIR /bodhi
CMD ["bash"]
COPY . /bodhi
RUN cp devel/development.ini.example bodhi-server/development.ini
RUN sed -i '/pyramid_debugtoolbar/d' bodhi-server/development.ini
