---
- hosts: all

  tasks:
    - name: install deps
      become: true
      tags:
        - prep
      dnf:
        name:
          - pungi
          - python3-psycopg2
          - python3-librepo
          - python3-pip
          - python3-createrepo_c
          - python3-dnf
          - python3-setuptools
          - python3-mock
          - python3-bugzilla
          - python3-fedora

    - name: prepare unit
      copy:
        src: "/workspace/{{ zuul.project.src_dir }}/devel/development.ini.example"
        dest: "/workspace/{{ zuul.project.src_dir }}/bodhi-server/development.ini"
        remote_src: yes
        force: no
        unsafe_writes: yes
      tags:
        - prep

    - name: prepare unit
      lineinfile:
        path: "/workspace/{{ zuul.project.src_dir }}/bodhi-server/development.ini"
        regexp: pyramid_debugtoolbar
        state: absent
        unsafe_writes: yes
      tags:
        - prep

    - name: install test dependencies
      pip:
        name:
          - webtest
          - pytest
          - pytest-cov
      tags:
        - prep

    - name: create venv
      command:
        chdir: "/workspace"
        cmd: "python3 -m venv --system-site-packages venv"
        creates: "/workspace/venv"
      tags:
        - prep

    - name: "hack: install some deps"
      pip:
        virtualenv: "/workspace/venv"
        name:
          # install celery separately because it has a versionned dep on setuptools
          - celery
          # for some reason pyasn1-modules is preventing pyasn1 from installing correctly if it's installed with the rest. Install it now.
          - pyasn1
      tags:
        - prep

    - name: Get Python 3 version
      command: python3 -c "import sys; print('%s.%s' % sys.version_info[0:2])"
      register: python3_version
      tags:
        - prep

    - name: setup bodhi
      command:
        chdir: "/workspace/{{ zuul.project.src_dir }}/{{ item }}"
        cmd: "/workspace/venv/bin/python3 setup.py develop"
        creates: /workspace/venv/lib/python{{ python3_version.stdout }}/site-packages/{{ item }}.egg-link
      loop:
        - bodhi-messages
        - bodhi-client
        - bodhi-server
      tags:
        - prep

    - name: run tests
      command:
        chdir: "/workspace/{{ zuul.project.src_dir }}/{{ item }}"
        cmd: "/workspace/venv/bin/python3 -m pytest -c ../setup.cfg"
      loop:
        - bodhi-messages
        - bodhi-client
        - bodhi-server
