---
- hosts: all

  tasks:
    - name: install pre-commit
      pip:
        name:
          - pre-commit
          - types-requests
          - types-click
      tags:
        - prep

    - name: run pre-commit
      command:
        chdir: "/workspace/{{ zuul.project.src_dir }}"
        cmd: pre-commit run --all
