"""Add a unique constraint to the Update.title

Revision ID: 3aae6532b560
Revises: 6383ec38980
Create Date: 2016-03-01 19:03:30.088491

"""

# revision identifiers, used by Alembic.
revision = '3aae6532b560'
down_revision = '6383ec38980'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_updates_title', table_name='updates')
    op.create_index(op.f('ix_updates_title'), 'updates', ['title'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updates_title'), table_name='updates')
    op.create_index('ix_updates_title', 'updates', ['title'], unique=False)
    ### end Alembic commands ###
