"""Add a User.email column

Revision ID: 52dcf7261a86
Revises: 479aaacfc5c7
Create Date: 2015-09-02 12:37:10.516974

"""

# revision identifiers, used by Alembic.
revision = '52dcf7261a86'
down_revision = '479aaacfc5c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
