
FROM registry.fedoraproject.org/fedora:f35
RUN dnf update -y && dnf install -y iproute rsync git traceroute unzip bzip2 make curl wget tar procps-ng which sudo unzip findutils grep ncurses-devel openssl-devel zlib-devel krb5-devel make cmake gcc gcc-c++ rpm-build rpm-sign expect python3-setuptools python3 python3-devel python3-wheel python3-pip && dnf clean all
