# Copyright (c) YEAR AUTHOR
#
# This file is part of Bodhi.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
"""
Add critical path Packages

Revision ID: a429f263fc3f
Revises: 58b7919b942c
Create Date: 2019-03-14 09:31:38.169232
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a429f263fc3f'
down_revision = '58b7919b942c'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critical_path_packages_table',
                    sa.Column('package_id', sa.Integer(), nullable=False),
                    sa.Column('release_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
                    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ))
    op.create_index(
        op.f('ix_critical_path_packages_table_package_id'),
        'critical_path_packages_table',
        ['package_id'],
        unique=False
    )
    op.create_index(
        op.f('ix_critical_path_packages_table_release_id'),
        'critical_path_packages_table',
        ['release_id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_critical_path_packages_table_release_id'),
        table_name='critical_path_packages_table'
    )
    op.drop_index(
        op.f('ix_critical_path_packages_table_package_id'),
        table_name='critical_path_packages_table'
    )
    op.drop_table('critical_path_packages_table')
    # ### end Alembic commands ###
