.TH "bodhi" "1" "2007 Dec 3" "Luke Macken" ""

.SH "NAME"
bodhi \- The bodhi client

.SH "SYNOPSIS"
\fBbodhi\fP [options] [build|package]
.PP

.SH "DESCRIPTION"
\fBbodhi\fP is the comment-line tool for interacting with a bodhi instance.

.SH "OPTIONS"
.IP "\fB\-n --new\fP"
Submit a new update
.IP "\fB\-e --edit\fP"
Edit an existing update
.IP "\fB\-b --bugs\fP BUG1,BUG2,.."
Specify any number of Bugzilla IDs (--bugs=1234,5678)
.IP "\fB\-r --release\fP RELEASE"
Specify a release [F7|F8]
.IP "\fB\-N --notes\fP NOTES"
Update notes
.IP "\fB\-t --type\fP TYPE"
Update type [bugfix|security|enhancement]
.IP "\fB\-u --username\fP USERNAME"
Login username for bodhi
.IP "\fB\-d --delete\fP"
Delete an update
.IP "\fB\--file\fP"
Get update details from a file
.IP "\fB\-c --comment\fP COMMENT"
Comment on an update
.IP "\fB\-k --karma\fP [+1|-1]"
Give karma to a specific update (default: 0)
.IP "\fB\-R --request\fP ACTION"
Request that an action be performed on an update [testing|stable|unpush|obsolete]
.IP "\fB\-m --mine\fP"
Display a list of your updates
.IP "\fB\-C --candidates\fP"
Display a list of your update candidates
.IP "\fB\-T --testable\fP"
Display a list of installed updates that you could test and provide feedback for
.IP "\fB\-M --masher\fP"
Display the status of the Masher (releng only)
.IP "\fB\-P --push\fP"
Display and push any pending updates (releng only)
.IP "\fB\-v --verbose\fP"
Show debugging messages
.IP "\fB\-l --limit\fP"
Maximum number of updates to return (default: 10)
.IP "\fB\-h --help\fP"
display the usage message

.SH "EXAMPLES"
Using the bodhi command-line interface
.br
https://fedorahosted.org/bodhi/wiki/CLI
.br

.PP 
.SH "AUTHORS"
.nf 
Luke Macken <lmacken@redhat.com>
.fi 

.PP 
.SH "BUGS"
Bugs should be filed in bodhi's Trac:
.br
https://fedorahosted.org/bodhi/newticket
.fi
