#!/usr/bin/env python3
"""
Generate an image of the database schema
"""
import os

from packaging import version
from sqlalchemy import create_engine
from sqlalchemy_schemadisplay import create_schema_graph
try:
    from sqlalchemy_schemadisplay import __version__ as sqlschemaver
except ImportError:
    sqlschemaver = '1.0'

from bodhi.server import models


DOCS_DIR = os.path.dirname(__file__)


def write_graph(filename):
    if version.parse(sqlschemaver) >= version.parse('2.0'):
        graph = create_schema_graph(
            engine=create_engine('sqlite:///:memory:'),
            metadata=models.metadata,
            show_datatypes=False,
            show_indexes=False,
            rankdir='LR',
            concentrate=False
        )
    else:
        graph = create_schema_graph(
            metadata=models.metadata,
            show_datatypes=False,
            show_indexes=False,
            rankdir='LR',
            concentrate=False
        )
    graph.write_png(filename)


if __name__ == '__main__':
    write_graph(f'{DOCS_DIR}/generated/database.png')
