# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

shopt -s expand_aliases
alias bdocs="make -C /bodhi/docs clean && make -C /bodhi/docs html && make -C /bodhi/docs man"
alias blog="journalctl -u bodhi -u fm-consumer@config"
alias brestart="systemctl restart bodhi.service celery.service fm-consumer@config.service fm-consumer@printer.service && echo 'The application is running on http://localhost.localdomain:6543'"
alias bstart="systemctl start bodhi.service celery.service fm-consumer@config.service fm-consumer@printer.service && echo 'The application is running on http://localhost.localdomain:6543'"
alias bstop="systemctl stop bodhi.service celery.service fm-consumer@config.service fm-consumer@printer.service"
alias blint="pre-commit run -a"
alias bmessages="journalctl -u fm-consumer@printer -f"
alias bodhi-shell="python3 /usr/bin/pshell /etc/bodhi/production.ini"


function bresetdb {
    bstop;
    psql -U postgres -h localhost -c "DROP DATABASE bodhi2";
    createdb -U postgres -h localhost bodhi2;
    if [ ! -f "/tmp/bodhi2.dump.xz" ] ; then
        curl -o /tmp/bodhi2.dump.xz https://infrastructure.fedoraproject.org/infra/db-dumps/bodhi2.dump.xz
    fi
    xzcat /tmp/bodhi2.dump.xz | psql -U postgres -h localhost bodhi2;
    pushd /bodhi/bodhi-server;
    # we call 'python3' explicitly to dodge some options in the
    # shebang which break finding our bodhi modules
    python3 /usr/bin/alembic upgrade head;
    popd;
    bstart;
}


function btest {
    find /bodhi -name "*.pyc" -delete;
    pushd /bodhi
    blint || return $?
    bdocs || return $?
    for module in bodhi-messages bodhi-client bodhi-server; do
        pushd $module
        python3 -m pytest $@ tests || return $?
        popd
    done
    diff-cover bodhi-*/coverage.xml --compare-branch=develop --fail-under=100
    popd
}


export BODHI_URL="http://localhost.localdomain:6543/"
export BODHI_OPENID_PROVIDER="http://localhost.localdomain:6546/openidc"
export PYTHONWARNINGS="once"
export BODHI_CI_ARCHIVE_PATH="/bodhi-ci-test_results/"

cat /etc/motd
cd /bodhi
