amqp_url = "amqp://"
publish_exchange = "amq.topic"
callback = "bodhi.server.consumers:Consumer"

[[bindings]]
queue = "bodhi_local_queue"
exchange = "amq.topic"
routing_keys = [
    "org.fedoraproject.*.bodhi.update.edit",
    "org.fedoraproject.*.bodhi.update.request.testing",
    "org.fedoraproject.*.waiverdb.waiver.new"
]

[tls]
ca_cert = "/etc/pki/tls/certs/ca-bundle.crt"
keyfile = "/my/client/key.pem"
certfile = "/my/client/cert.pem"

[client_properties]
app = "Bodhi dev local"

[queues.bodhi_local_queue]
durable = true
auto_delete = false
exclusive = false
arguments = {}

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "WARNING"
handlers = ["console"]
