amqp_url = "amqps://fedora:@rabbitmq.fedoraproject.org/%2Fpublic_pubsub"
callback = "bodhi.server.consumers:Consumer"

[exchanges."amq.topic"]
type = "topic"
durable = true
auto_delete = false
arguments = {}

# Note the double brackets below.
# To add another binding, add another [[bindings]] section.
[[bindings]]
queue = "bodhi_remote_queue"
exchange = "amq.topic"
routing_keys = [
    "org.fedoraproject.*.buildsys.tag",
    "org.fedoraproject.*.resultsdb.result.new"
]

[tls]
ca_cert = "/etc/fedora-messaging/cacert.pem"
keyfile = "/etc/fedora-messaging/fedora-key.pem"
certfile = "/etc/fedora-messaging/fedora-cert.pem"

[client_properties]
app = "Bodhi dev remote"

[queues.bodhi_remote_queue]
durable = true
auto_delete = false
exclusive = false
arguments = {}

[qos]
prefetch_size = 0
prefetch_count = 25

[log_config]
version = 1
disable_existing_loggers = true

[log_config.formatters.simple]
format = "[%(name)s %(levelname)s] %(message)s"

[log_config.handlers.console]
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[log_config.loggers.fedora_messaging]
level = "INFO"
propagate = false
handlers = ["console"]

[log_config.root]
level = "WARNING"
handlers = ["console"]
