name: Auto-approve Dependabot PRs
on:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-approve:
    name: Auto-approve minor and patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor # includes patch updates!
          approve: true
